#!/bin/bash

export $(dbus-launch)

mkdir -p /home/steam/.local/share/Steam

if [ "${CONTAINERD}" = "docker" ]; then
    chown -R steam:steam "/home/steam/.local/share/Steam"
    sudo -u steam "$@"
else
    "$@"
fi

