#!/bin/bash

EXTRA_OPTIONS=""
if [ "${UID}" = "0" ]; then
    EXTRA_OPTIONS="${EXTRA_OPTIONS} -e CHOWN=1"
fi

if which podman; then
    # https://github.com/NVIDIA/nvidia-container-runtime/issues/85#issuecomment-604931556
    CONTAINERD="podman"
    GPU_OPTIONS="--security-opt=label=disable --hooks-dir=/usr/share/containers/oci/hooks.d/"
    # see https://github.com/containers/podman/issues/7801
    GPU_OPTIONS="${GPU_OPTIONS} --security-opt=unmask=ALL --volume=/dev:/dev"
    ROOT_FOLDER="/root"
elif which docker; then
    # https://github.com/NVIDIA/nvidia-docker

    CONTAINERD="docker"
    GPU_OPTIONS="--gpus all"
    ROOT_FOLDER="/home/steam"

    # TODO: check is docker in rootless mode
    EXTRA_OPTIONS="${EXTRA_OPTIONS} -e CHOWN=1"
else
    echo "no container manager found"
    exit 1
fi

if ! which pactl > /dev/null 2>&1; then
    echo "Please Install Pulseaudio"
    exit 127
fi
PULSEAUDIO_SOCKET_PATH="${XDG_RUNTIME_DIR}/pulse/native"

if ! [ -S "${PULSEAUDIO_SOCKET_PATH}" ]; then
    rm -rf "${PULSEAUDIO_SOCKET_PATH}"
    mkdir -p "$(dirname ${PULSEAUDIO_SOCKET_PATH})"
    pactl load-module module-native-protocol-unix socket="${PULSEAUDIO_SOCKET_PATH}"
fi

if ${CONTAINERD} container inspect steam > /dev/null 2>&1; then
    ${CONTAINERD} start steam;
else
    ${CONTAINERD} build -t localhost/steam --build-arg USER_UID=$(id -u) --build-arg USER_GID=$(id -g) "$(dirname "$0")"

    ${CONTAINERD} run --name steam ${GPU_OPTIONS} \
        -v "${PULSEAUDIO_SOCKET_PATH}:/tmp/pulseaudio.socket:rw" \
        -e DISPLAY=$DISPLAY \
        -e XAUTHORITY=/home/steam/.Xauthority \
        -e CONTAINERD="${CONTAINERD}" \
        -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
        -v $XAUTHORITY:/home/steam/.Xauthority \
        --shm-size=$(free -g | head -n 2 | tail -n 1 | awk '{ print $2 }')G \
        --privileged \
        -v $(pwd)/steam:${ROOT_FOLDER}/.local/share/Steam \
        ${EXTRA_OPTIONS} \
        localhost/steam
fi
